### ISSUE TITLE
SaveAs file error (Excel cell max length 32,767 characters)

### ISSUE THREAD

**Issue by shps951023** [shps951023/MiniExcel#327]
![image](https://user-images.githubusercontent.com/12729184/153690713-5cd39ecf-b349-499e-9b9b-15655c26f2ec.png)

**Comment by shps951023** [comment]
v1.22.0 will fix this

**Comment by db2222** [comment]
@shps951023 I have this exact issue with the newest version. The difference however is that it is a string and not a byte array column.

Is it a new/further bug or are specific settings needed if one has such a long text?

Thank you in advance!

**Comment by db2222** [comment]
I have found time to analyze it further. It has nothing to do with MiniExcel. It's a limitation of Excel itself.
During my initial short research a few days ago I found this ticket and misinterpreted it as an issue with MiniExcel.

The workaround is for instance to use CSV instead of Excel which is also possible with this library.
